---
apiVersion: v1
# created manually using the command:
# oc create configmap --from-file=config.yaml monocle-config --dry-run=client -oyaml
kind: ConfigMap
metadata:
  name: monocle-config
  labels:
    app.kubernetes.io/part-of: monocle
data:
  config.yaml: |+
    workspaces:
      - name: inmarket
        crawlers:
          - name: NinthDecimal
            provider:
              github_organization: NinthDecimal
            update_since: '2023-01-01'
          - name: ThinkNear
            provider:
              github_organization: ThinkNear
            update_since: '2023-01-01'
        projects:
          - name: NinthDecimal
            repository_regex: ".*NinthDecimal/.*"
          - name: ThinkNear
            repository_regex: ".*ThinkNear/.*"
        search_aliases:
          - name: bots
            alias: '(author:"inmarket-cloud" or
              author:"nd-sysadmin" or 
              author:"thinknear-atlantis-user" or 
              author:"thinknear-atlantis" or 
              author:"thinknear-jenkins-2"
              )'
